### ISSUE TITLE
Does not generate feed links correctly for in-browser TW

### ISSUE THREAD

**Issue by dullroar** [dullroar/TW5-atomfeed#1]
The original implementation was meant to be used when generating a static site using node. However, since it works in-browser, too, its behavior should probably detect when it is being used in-browser and generate permalinks to tiddlers in that case instead of URLs pointing to specific static HTML files.

**Comment by sukima** [comment]
How would it work **in browser** the `atom.xml` is a separate file. I can see an export type allowing someone to download the `atom.xml` which is the same as the Node,js version generating it.

In either case I find linking to the permalink might be better even in the node version. I would want my feed reader to link to the permalink. So if my feed reader is reading (for example only since I don't have this working yet): `https://tritarget.org/atom.xml` then the links in there should link to `https://tritarget.org/#My%20Tiddler` not `https://tritarget.org/static/My%20Tiddler.html` that way when you click on the item you get the full single page TiddlyWiki and not some orphaned static file. Unless that is really what you want. Perhaps this should be an option.

Does atom support alternative links?

**Comment by dullroar** [comment]
It looks like it - search for "alternate" at https://tools.ietf.org/html/rfc4287. That said, the original use case was for TW under node, where I was trying to use it to generate a static web site (so each tiddler would be a separate HTML file, and hence not need a TW permalink). I have since moved on to another mechanism and am not using TW any more. I have left the repo out here in case someone found it useful (and apparently you do - cool!)

So, that said, and having just merged in your pull request, I think there are a couple of paths, if you wanted to take a stab at it:

* You could fork the project. I have no problem with that, but it may "muddy the water" if there are two projects floating around doing the same thing.
* You could send me pull requests, and I would be happy to merge them in.
* I could make you a commiter to this project and eliminate the middle man (I'd glance at your commits, but probably no more than I did with the pull request). Having glanced at your work on GitHub, I would not have a problem with that.

Comments? Preferences?

**Comment by sukima** [comment]
Well the nature of github is that it is already forked. Though based on the google groups links yours is the canonical version.

I am comfortable with either pull requests or being a contributor. So that depends on your preference. Being a contributor does make it easier but it also means there is an added step to discussion points.

My typical M.O. When collaborating on projects is to always make changes in pull requests (even as a contributor) so that team mates can discuss, review, etc. it also allows watchers to keep upto date. It also makes nice history easy and reverts easier. For you went this route I'd probably wait about a day for feedback till I auto merged when I felt comfortable. (I get paid with :shipit: ).

On a different note, If this plugin prove useful in my homepage I would consider the idea of incorporating it into the core plugin library. There is a work-in-progress blog plugin in the main repo that would benefit.

**Comment by dullroar** [comment]
Yeah, I know forking is natural, but what I was talking about was the links on the Google group, and not wanting to confuse things there. If it ultimately became part of the core plugin lib I am fine with that, also. In the mean time, I am going to make you a contributor. I like the workflow you mention above of making pull requests, and if I don't respond just consider that my tacit "approval."

**Comment by sukima** [comment]
I think has been fixed by #7. It uses the permalink as the main href and the static link for the *alternate* href.
